### ISSUE TITLE
php 7.1 composer update problem

### ISSUE THREAD

**Issue by xklid101** [aleswita/VisualPaginator#1]
Hi, after my PHP upgrade to 7.1, I wanted to "composer update", but it shows following error message

```
Problem 1
- aleswita/visualpaginator dev-master requires php ~7.0.0 -> your PHP version (7.1.0) does not satisfy that requirement.
```

Could you please update your composer.json to require php ~7.1.0? Or does it really work only under ~7.0.0?

**Comment by aleswita** [comment]
Hi, try **$ composer update** now.

**Comment by xklid101** [comment]
It is ok now, thanks for fast fix
