### ISSUE TITLE
Do not include default values in URL

### ISSUE THREAD

**Issue by jtojnar** [aleswita/VisualPaginator#4]
URLs like `?paginator-page=1&paginator-itemsPerPage=10&do=paginator-paginate` are hideous, especially when we do not allow customizing `itemsPerPage`.

**Comment by jAKErCZ** [comment]
> URLs like `?paginator-page=1&paginator-itemsPerPage=10&do=paginator-paginate` are hideous, especially when we do not allow customizing `itemsPerPage`.

What you need?

**Comment by jtojnar** [comment]
I guess we would need to change how Nette generates links to exclude the parameters default with default value. Or possibly read and store the data from presenter's parameter instead of the component's.
