### ISSUE TITLE
VisualPaginator nette 3 - Definice itemsPerPage

### ISSUE THREAD

**Issue by jAKErCZ** [aleswita/VisualPaginator#5]
Ahoj,
řeším problém že nikde v readme nemáš napsané jak definovat itemsPerPage?? Jelikož mi tam automaticky definuje 1 na stránku..

Jak se to dá řešit?

Díky

**Comment by aleswita** [comment]
tady pres tu metodu by to melo jit

https://github.com/aleswita/VisualPaginator/blob/master/src/VisualPaginator.php#L155

**Comment by jAKErCZ** [comment]
No a to asi budu definovat zde že?
```
protected function createComponentPaginator(): VisualPaginator {
        $vp = new VisualPaginator;
        $vp::$paginatorTemplate = VisualPaginator::TEMPLATE_BOOTSTRAP_V4;
        $vp->setItemsPerPage('7');
        return $vp;
    }
```

Ale nette mi vrací

**Value '7' is out of allowed set [1, 2, 3] in field 'itemsPerPage'.**

**Comment by aleswita** [comment]
tak si to tam pridej

https://github.com/aleswita/VisualPaginator/blob/master/src/VisualPaginator.php#L76

je to public static promenna

`$vp:: $itemsPerPageList[7] = '7';`
