### ISSUE TITLE
$vp->onPaginate[] = function(): void Ajax vyhazuje Deprecated

### ISSUE THREAD

**Issue by jAKErCZ** [aleswita/VisualPaginator#6]
Zdravým,
mám problém při použití ajaxu dle dokumentace mi to vrací **Deprecated**
```
User Deprecated

Nette\Utils\Callback::invoke() is deprecated, use native invoking. 
```

Jak se toto dá vyřešit?

**Comment by aleswita** [comment]
pokud to ches pouzit, tak asi budes muset poslat PR s fixem
