### ISSUE TITLE
No way to get Paginator

### ISSUE THREAD

**Issue by jvitasek** [aleswita/VisualPaginator#9]
Hi, is there a reason why there is no getPaginator() method? I need to use the Nette\Utils\Paginator object in a different Latte template and cannot get to it without changing the accessor from private to public.

Can I create a PR adding a method to return the Nette\Utils\Paginator object?

Let me know.

**Comment by aleswita** [comment]
Hi.

There is no reason why getPaginator() method missing, you can add by PR, tnx.

**Comment by jvitasek** [comment]
Solved in ed0ebfd575fe06fde6436befd6b203c120052df4
